### ISSUE TITLE
Introduce concept of isomorphism?

### ISSUE THREAD

**Issue by edeykholt** [trustoverip/tswg-cesr-specification#43]
In many places in the spec, the concept of lossless, two-way conversion, especially between objects the binary and text domains.  Introducing the term isomorphic and using that spec might shorten the spec and/or lay an even stronger foundation, e.g. something like the following?:
- Any framed primitive instance in the text domain is isomorphic with an equivalent framed primitive instance in the binary domain.
- Any composition in the text domain is isomorphic with an equivalent composition in the binary domain.
- ... encode / decode
- ... compose / decompose
- .... multiplex / demultiplex

There might also be some polymorphic transformations in the spec that could be called out as such, or conversions to/from some external representations that would not round-trip exactly?

**Comment by m00sey** [comment]
There is a lot of re-write that would need to occur to change from lossless - we'll review PRs that address this as seen.

**Comment by pfeairheller** [comment]
Lossless is good enough
