### ISSUE TITLE
Explicitly call out undefined behavior in "Universal Code table genus/version codes that allow genus/version override" section?

### ISSUE THREAD

**Issue by daidoji** [trustoverip/tswg-cesr-specification#58]
In `Universal Code table genus/version codes that allow genus/version override` section we have:

> All genera shall have the following codes in their Count Code table. Should the first Group Code embedded in each of these groups be a genus/version code then the parser shall switch code tables to the code table given by that genus/version code.

What happens if a genus/version code isn't the first element group code but shows up in the nth + 1 element group code?  Is this strictly undefined/ignored/or do we switch tables sometimes/always?  

Probably explicitly defining this or noting that its undefined is the way to go.

**Comment by pfeairheller** [comment]
"the enclosing group should be dropped"

**Comment by SmithSamuelM** [comment]
I know I said it should be dropped, in the meeting but after more thought I  realized this is wrong.
The presence of a genus/version count code that appears first after a universal count code that is not an overridable universal count code has no special meaning to the parser. The parser's interpretation of its presence  is dependent on the the non-overriddable universal count code context. A parser does not treat it special. For example suppose the universal count code is a list. In some applications of the list count code it may be desirable that the  first element of the list may be a genus/version code. The presence provides no special meaning to the parser.

**Comment by SmithSamuelM** [comment]
Completed with #81
